export enum repositories {
    admin_repository = 'admin_repository',
    owner_repository = 'owner_repository',
    type_repository = 'Type_repository',
    typeLanguage_repository = 'typeLanguage_repository',
    store_repository = 'store_repository',
    category_repository = 'category_repository',
    product_repository = 'product_repository',
    pickupMethod_repository = 'pickupMethod_repository',
    openingHour_repository = 'openingHour_repository',
    productImage_repository = 'productImage_repository',
    productExtra_repository = 'productExtra_repository',
    productInstruction_repository = 'productInstruction_repository',
    productVariant_repository = 'productVariant_repository',
    offer_repository = 'offer_repository',
    customer_repository = 'customer_repository',
    otpCode_repository = 'otpCode_repository',
    cart_repository = 'cart_repository',
    cartItem_repository = 'cartItem_repository',
    cartItemVariant_repository = 'cartItemVariant_repository',
    cartItemExtra_repository = 'cartItemExtra_repository',
    cartItemInstruction_repository = 'cartItemInstruction_repository',
    avatar_repository='avatar_repository'
}